"""
integrations/google_calendar.py — Google Calendar API wrapper.

Multi-user auth follow-up: this used to cache one googleapiclient
Resource for the whole process, built from a single credentials.json /
token.json pair on disk -- correct for a single local user, wrong for
a real web app where each user connects their own Google account.
Every function below now takes an explicit `service` (or, for the
OAuth handshake itself, works with a `Credentials` object) rather than
reaching for a process-global singleton, so callers
(services/calendar_sync_service.py) are responsible for getting the
right user's service via get_service_for_user() first.

Three pieces:
- OAuth handshake: build_authorization_url() / exchange_code() drive a
  standard web-application OAuth flow (Authorization Code grant,
  access_type=offline so a refresh token comes back) -- the frontend
  sends the user to the URL from the first, Google redirects back to
  api/calendar.py's callback route with a `code`, which the second
  exchanges for Credentials. The resulting Credentials.to_json() blob
  is what services/integration_credentials_service.py persists per
  user; this module never touches the database itself.
- get_service_for_user(): loads a user's stored credentials JSON,
  transparently refreshes an expired access token, and returns
  (service, refreshed_credentials_json_or_None) -- the caller persists
  the second value back via integration_credentials_service only when
  it isn't None (i.e. only when a refresh actually happened).
- The actual Calendar API operations (list_events, get_free_busy,
  create_event, update_event, delete_event), each taking `service` as
  returned above.

Every public function can raise GoogleCalendarNotConfigured (no
GOOGLE_CALENDAR_CLIENT_ID/SECRET set, or this user hasn't connected
their calendar yet) or the more general GoogleCalendarError (API call
failed). Callers -- mainly services/calendar_sync_service.py -- catch
these and degrade gracefully rather than letting a missing/unconnected
integration take down the scheduler.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple, TypedDict

from backend import config

logger = logging.getLogger(__name__)


class GoogleCalendarError(RuntimeError):
    """Raised when an authenticated call to the Google Calendar API fails."""


class GoogleCalendarNotConfigured(GoogleCalendarError):
    """
    Raised when the app-wide OAuth client isn't configured
    (GOOGLE_CALENDAR_CLIENT_ID/SECRET unset) or this particular user
    hasn't connected their Google Calendar yet. Expected in both cases
    -- Calendar sync is opt-in -- so callers should treat it as
    "feature not turned on for this user", not a crash.
    """


class RemoteEvent(TypedDict):
    google_event_id: str
    title: str
    start: datetime
    end: datetime


# ---------------------------------------------------------------------------
# OAuth handshake (web application flow, one connection per user)
# ---------------------------------------------------------------------------

def is_oauth_client_configured() -> bool:
    return bool(config.GOOGLE_CALENDAR_CLIENT_ID and config.GOOGLE_CALENDAR_CLIENT_SECRET)


def _client_config() -> Dict[str, Any]:
    if not is_oauth_client_configured():
        raise GoogleCalendarNotConfigured(
            "GOOGLE_CALENDAR_CLIENT_ID / GOOGLE_CALENDAR_CLIENT_SECRET are not set. "
            "Create a Web application OAuth client in Google Cloud Console "
            "(APIs & Services -> Credentials), add "
            f"{config.GOOGLE_CALENDAR_REDIRECT_URI} as an authorized redirect URI, "
            "then set both env vars. See INTEGRATIONS.md."
        )
    return {
        "web": {
            "client_id": config.GOOGLE_CALENDAR_CLIENT_ID,
            "client_secret": config.GOOGLE_CALENDAR_CLIENT_SECRET,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [config.GOOGLE_CALENDAR_REDIRECT_URI],
        }
    }


def _new_flow(state: Optional[str] = None):
    """
    A fresh OAuth Flow for this app's web client. PKCE auto-generation is
    turned off deliberately: the authorization URL and the code exchange
    happen in two different HTTP requests (build_authorization_url() vs.
    the callback route), so two different Flow instances -- and a code
    verifier generated by the first is gone by the time the second one
    needs it, which makes Google reject the exchange ("Missing code
    verifier"). This is a confidential client (it has a client secret), so
    PKCE isn't required; `state` (a signed, short-lived token) is what ties
    the callback back to the right user.
    """
    from google_auth_oauthlib.flow import Flow

    flow = Flow.from_client_config(
        _client_config(),
        scopes=config.GOOGLE_CALENDAR_SCOPES,
        state=state,
        autogenerate_code_verifier=False,
    )
    flow.redirect_uri = config.GOOGLE_CALENDAR_REDIRECT_URI
    return flow


def build_authorization_url(state: str) -> str:
    """
    The URL to send the user's browser to for the Google consent
    screen. `state` round-trips through Google back to the callback
    route unmodified -- api/calendar.py signs the current user's id
    into it (a short-lived JWT) so the callback, which Google calls
    with no Authorization header of its own, knows which account to
    attach the resulting credentials to.
    """
    flow = _new_flow(state=state)
    # access_type=offline is what actually gets a refresh_token back;
    # prompt=consent forces the consent screen (and a fresh
    # refresh_token) even for a user who authorized this app before,
    # since Google otherwise silently omits it on a repeat grant.
    url, _state = flow.authorization_url(
        access_type="offline", include_granted_scopes="true", prompt="consent"
    )
    return url


def exchange_code(code: str) -> str:
    """
    Exchange the authorization `code` Google's redirect handed back for
    real credentials. Returns the Credentials.to_json() blob to persist
    via services/integration_credentials_service.save_google_credentials_json.
    """
    flow = _new_flow()
    try:
        flow.fetch_token(code=code)
    except Exception as exc:  # noqa: BLE001 - oauthlib raises several distinct exception types
        raise GoogleCalendarError(f"Google Calendar OAuth code exchange failed: {exc}") from exc
    return flow.credentials.to_json()


# ---------------------------------------------------------------------------
# Per-user service construction
# ---------------------------------------------------------------------------

def get_service_for_user(credentials_json: Optional[str]) -> Tuple[Any, Optional[str]]:
    """
    Build a Calendar v3 API client from a user's stored credentials
    JSON (see integration_credentials_service.get_google_credentials_json).

    Returns (service, refreshed_credentials_json). The second element
    is None unless the access token had expired and was refreshed in
    this call, in which case it's the new JSON the caller must persist
    back (via integration_credentials_service.save_google_credentials_json)
    so the next call doesn't have to refresh again.

    Raises GoogleCalendarNotConfigured if the user hasn't connected
    their calendar yet (credentials_json is None) or the refresh token
    was revoked and there's nothing to refresh from.
    """
    if not credentials_json:
        raise GoogleCalendarNotConfigured(
            "This account hasn't connected Google Calendar yet. Connect it from Settings."
        )

    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build

    creds = Credentials.from_authorized_user_info(
        json.loads(credentials_json), config.GOOGLE_CALENDAR_SCOPES
    )

    refreshed_json: Optional[str] = None
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except Exception as exc:  # noqa: BLE001 - google-auth raises RefreshError and friends
                raise GoogleCalendarNotConfigured(
                    "Google Calendar access expired and couldn't be refreshed -- "
                    "reconnect it from Settings."
                ) from exc
            refreshed_json = creds.to_json()
        else:
            raise GoogleCalendarNotConfigured(
                "Google Calendar credentials are invalid and can't be refreshed -- "
                "reconnect it from Settings."
            )

    service = build("calendar", "v3", credentials=creds, cache_discovery=False)
    return service, refreshed_json


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_event_datetime(node: Dict[str, str]) -> datetime:
    """
    Google returns either {"dateTime": "...", "timeZone": "..."} for timed
    events or {"date": "YYYY-MM-DD"} for all-day events. Normalize both to
    a UTC-aware datetime so downstream code (scheduler_service._as_utc)
    never has to special-case Google's shape.
    """
    if "dateTime" in node:
        return datetime.fromisoformat(node["dateTime"].replace("Z", "+00:00")).astimezone(timezone.utc)
    # All-day event: treat as midnight-to-midnight UTC.
    return datetime.fromisoformat(node["date"]).replace(tzinfo=timezone.utc)


def _run(request, *, action: str):
    from googleapiclient.errors import HttpError

    try:
        return request.execute()
    except HttpError as exc:
        raise GoogleCalendarError(f"Google Calendar API error during {action}: {exc}") from exc


# ---------------------------------------------------------------------------
# Public API -- every function takes the `service` returned by
# get_service_for_user() for whichever user is currently being synced.
# ---------------------------------------------------------------------------

def list_events(service: Any, start: datetime, end: datetime) -> List[RemoteEvent]:
    """
    Full event details (id, title, start, end) for the user's configured
    calendar in [start, end), skipping cancelled events. Used to populate
    the local CalendarEvent cache (source=GOOGLE) -- see calendar_sync_service.
    """
    events: List[RemoteEvent] = []
    page_token: Optional[str] = None

    while True:
        request = service.events().list(
            calendarId=config.GOOGLE_CALENDAR_ID,
            timeMin=start.astimezone(timezone.utc).isoformat(),
            timeMax=end.astimezone(timezone.utc).isoformat(),
            singleEvents=True,
            orderBy="startTime",
            pageToken=page_token,
        )
        result = _run(request, action="list_events")

        for item in result.get("items", []):
            if item.get("status") == "cancelled":
                continue
            if "start" not in item or "end" not in item:
                continue  # malformed/edge-case event, skip rather than crash the sync
            events.append(
                RemoteEvent(
                    google_event_id=item["id"],
                    title=item.get("summary") or "(untitled)",
                    start=_parse_event_datetime(item["start"]),
                    end=_parse_event_datetime(item["end"]),
                )
            )

        page_token = result.get("nextPageToken")
        if not page_token:
            break

    return events


def get_free_busy(service: Any, start: datetime, end: datetime) -> List[tuple]:
    """
    Busy (start, end) intervals only -- cheaper than list_events() when the
    caller (scheduler) doesn't need titles, just what's occupied. Uses the
    dedicated freebusy endpoint rather than filtering list_events().
    """
    body = {
        "timeMin": start.astimezone(timezone.utc).isoformat(),
        "timeMax": end.astimezone(timezone.utc).isoformat(),
        "items": [{"id": config.GOOGLE_CALENDAR_ID}],
    }
    result = _run(service.freebusy().query(body=body), action="get_free_busy")
    busy = result["calendars"][config.GOOGLE_CALENDAR_ID].get("busy", [])
    return [
        (_parse_event_datetime({"dateTime": b["start"]}), _parse_event_datetime({"dateTime": b["end"]}))
        for b in busy
    ]


def create_event(
    service: Any, title: str, start: datetime, end: datetime, description: Optional[str] = None
) -> str:
    """Create an event on the user's configured calendar. Returns the new google_event_id."""
    body: Dict[str, Any] = {
        "summary": title,
        "start": {"dateTime": start.astimezone(timezone.utc).isoformat()},
        "end": {"dateTime": end.astimezone(timezone.utc).isoformat()},
    }
    if description:
        body["description"] = description

    created = _run(
        service.events().insert(calendarId=config.GOOGLE_CALENDAR_ID, body=body),
        action="create_event",
    )
    return created["id"]


def update_event(
    service: Any,
    google_event_id: str,
    *,
    title: Optional[str] = None,
    start: Optional[datetime] = None,
    end: Optional[datetime] = None,
) -> None:
    """Patch an existing event -- only the fields provided are changed."""
    body: Dict[str, Any] = {}
    if title is not None:
        body["summary"] = title
    if start is not None:
        body["start"] = {"dateTime": start.astimezone(timezone.utc).isoformat()}
    if end is not None:
        body["end"] = {"dateTime": end.astimezone(timezone.utc).isoformat()}
    if not body:
        return

    _run(
        service.events().patch(calendarId=config.GOOGLE_CALENDAR_ID, eventId=google_event_id, body=body),
        action="update_event",
    )


def delete_event(service: Any, google_event_id: str) -> None:
    """
    Delete an event. Google returns 404/410 for events already deleted or
    long expired -- treated as success (the desired end state already
    holds) rather than surfaced as an error to the caller.
    """
    from googleapiclient.errors import HttpError

    try:
        service.events().delete(calendarId=config.GOOGLE_CALENDAR_ID, eventId=google_event_id).execute()
    except HttpError as exc:
        if exc.resp is not None and exc.resp.status in (404, 410):
            return
        raise GoogleCalendarError(f"Google Calendar API error during delete_event: {exc}") from exc
