"""
models/project.py — SQLAlchemy model for Project.

A Project groups related tasks (e.g. "SourceUp", "Interview Prep",
"Fitness"). It can be created manually via a brain dump, or generated by
the Goal Engine from a single high-level goal (goal_text is set in that
case, otherwise null).
"""

from __future__ import annotations

from typing import List, Optional, TYPE_CHECKING

from sqlalchemy import String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database import Base
from backend.models.enums import ProjectStatus, sa_enum
from backend.models.mixins import TimestampMixin

if TYPE_CHECKING:
    from backend.models.task import Task


class Project(Base, TimestampMixin):
    __tablename__ = "projects"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    status: Mapped[ProjectStatus] = mapped_column(
        sa_enum(ProjectStatus), default=ProjectStatus.ACTIVE, nullable=False
    )

    # Set when this project was generated by the Goal Engine (Milestone 4)
    # from a single high-level goal, e.g. "Get placed as an AI Engineer".
    goal_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    tasks: Mapped[List["Task"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Project id={self.id} name={self.name!r} status={self.status.value}>"
