"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 03:15:57.322873
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('buffer_multiplier', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_plans_plan_date'), ['plan_date'], unique=True)

    op.create_table('episodic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('weekly_review', 'project_completed', 'milestone', 'planning_decision', name='episodiceventtype'), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productivity_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_planned', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('most_productive_hour', sa.Integer(), nullable=True),
    sa.Column('estimation_error_pct', sa.Float(), nullable=True),
    sa.Column('execution_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_productivity_metrics_date')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'completed', name='projectstatus'), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('semantic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('project_template', 'recurring_workflow', name='semanticrelationtype'), nullable=False),
    sa.Column('subject_project_id', sa.Integer(), nullable=True),
    sa.Column('object_project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'blocked', 'completed', 'cancelled', 'archived', name='taskstatus'), nullable=False),
    sa.Column('importance', sa.Enum('low', 'medium', 'high', 'critical', name='importance'), nullable=False),
    sa.Column('energy_requirement', sa.Enum('low', 'medium', 'high', name='energylevel'), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommended_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_safe_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('completion_probability', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('context_switch_cost', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('skip_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('brain_dump', 'google', 'manual', name='eventsource'), nullable=False),
    sa.Column('sync_status', sa.Enum('not_synced', 'synced', 'error', name='syncstatus'), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_dependency_pair')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('predicted_hours', sa.Float(), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('error_pct', sa.Float(), nullable=True),
    sa.Column('predicted_priority_score', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'blocked', 'completed', 'cancelled', 'archived', name='taskstatus'), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('predicted_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_sessions')
    op.drop_table('subtasks')
    op.drop_table('predictions')
    op.drop_table('dependencies')
    op.drop_table('calendar_events')
    op.drop_table('tasks')
    op.drop_table('semantic_memory')
    op.drop_table('settings')
    op.drop_table('projects')
    op.drop_table('productivity_metrics')
    op.drop_table('episodic_memory')
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_plans_plan_date'))

    op.drop_table('daily_plans')
    # ### end Alembic commands ###
